### ISSUE TITLE
Model weight file

### ISSUE THREAD

**Issue by ChunGaoY** [CR-Ko/Vehicle-Distance-Detection#2]
Hello,
Is the network of this program built on YOLO v2? Since my device has limited computing power, can you send me a training weight file for the program? According to the program, it should be a file with a .h5 suffix. Looking forward to your reply.

**Comment by kkk324** [comment]
What's your device?

**Comment by ChunGaoY** [comment]
Currently my device is GPU MX130 and I cannot train the model. I hope you can send me a trained model. Thank you for your reply.

**Comment by kkk324** [comment]
You can try darknet to train your own model. It is quite simple. I have moved my project to unknown disk. I will send u if i find it.
